

UPDATE TALUNO SET
ESTADO = 'AC',
SALARIO = 250
WHERE COD_ALUNO = 1;

UPDATE TALUNO SET
ESTADO ='SP',
SALARIO = 460
WHERE COD_ALUNO =4;

SELECT * FROM TALUNO
WHERE ESTADO= 'PE'
AND SALARIO <=2000
ORDER BY cod_aluno  ASC ;


INSERT INTO taluno (cod_aluno, nome, cidade)
VALUES (seq_aluno.nextval, 'VALDO', 'DOIS IRMAOS');

INSERT INTO taluno (cod_aluno, nome, cidade)
VALUES (seq_aluno.nextval, 'EWERTON', 'DOIS IRMAOS');
INSERT INTO taluno (cod_aluno, nome, cidade)
VALUES (seq_aluno.nextval, 'VINICIUS', 'DOIS IRMAOS');


UPDATE taluno SET

ESTADO ='SP',
SALARIO = 900,
NOME ='PEDRO'
WHERE COD_ALUNO = 25;

SELECT ESTADO, SALARIO, NOME FROM TALUNO
ORDER BY ESTADO, SALARIO DESC;

-- criei um campo nascimento e usando o tipo DATE e por DEFAULT SYSDATE  -3000  PEGANDO TODOS OS
-- ALUNOS DESSA TABELA TALUNO E FAZENDO DECRESCER 3000 DIAS PARTINDO DA DATA ATUAL---

ALTER TABLE TALUNO ADD NASCIMENTO DATE DEFAULT SYSDATE -3000;
   ---
   ---- AQUI CONSEGUI SUBTRAIR
   UPDATE TALUNO SET
NASCIMENTO = SYSDATE -7000;
WHERE COD_ALUNO=15;


UPDATE TALUNO SET
NASCIMENTO='15/1/1993'
WHERE COD_ALUNO=8;

UPDATE TALUNO SET
NASCIMENTO = '10/08/2000 10:56:10'
 WHERE COD_ALUNO = 2;

UPDATE TALUNO SET
NASCIMENTO = '10/08/2001'
WHERE COD_ALUNO=3     ;


SELECT * FROM TALUNO
WHERE COD_ALUNO= 3;

SELECT * FROM titem
WHERE cod_curso IN (1,2,4);

SELECT * FROM titem
WHERE cod_curso NOT IN (1,2,4);

INSERT INTO tcurso VALUES (5, 'WINDOWS', 1000,50);

--- CURSO NAO VENDIDOS 0-----
SELECT * FROM TCURSO
WHERE COD_CURSO NOT IN (SELECT COD_CURSO FROM TITEM);

--- CURSO  VENDIDOS 0-----
SELECT * FROM TCURSO
WHERE COD_CURSO IN (SELECT COD_CURSO FROM TITEM);


SELECT * FROM tcurso InitCap
 WHERE  nome LIKE 'W%';

 SELECT * FROM tcurso
 WHERE nome LIKE '%JAVA%';

 SELECT * FROM tcurso
 WHERE nome LIKE '%FACES%';

 COMMIT;
 ROLLBACK;


 SELECT * FROM TALUNO;

SELECT COD_ALUNO, NOME, SOBRENOME,ESTADO, CIDADE,CEP,SALARIO, NASCIMENTO
FROM TALUNO;

SELECT * FROM TCURSO;

 ALTER TABLE TCURSO ADD PRE_REQ INTEGER;
 ALTER TABLE TALUNO ADD SOBRENOME VARCHAR2(100);

 ALTER TABLE TALUNO modify Column SOBRENOME AFTER NOME;

 UPDATE TALUNO SET
 SOBRENOME = 'NEVES'
 WHERE COD_ALUNO =1;

 UPDATE TCURSO SET
 PRE_REQ=1
 WHERE COD_CURSO =2;


 UPDATE TCURSO SET
 PRE_REQ=3
 WHERE COD_CURSO =4;

 SELECT * FROM tcurso WHERE pre_req IS NULL; --- pre- requisito nulo

  SELECT * FROM tcurso WHERE pre_req IS NOT NULL;  --- pre- requisito não nulo


  -- precedencia de opearadores
  ---()
  --- and
  --- or

  SELECT * FROM TCURSO
  WHERE VALOR > 750
  OR VALOR <1000
  AND CARGA_HORARIA = 25;


  SELECT * FROM TCURSO
  WHERE (VALOR > 750
  OR VALOR <1000  )
  AND CARGA_HORARIA = 25;

SELECT cod_aluno,nascimento,Trunc(nascimento), nome
FROM taluno
WHERE Trunc(nascimento) <> '29/08/2002'
ORDER BY cod_aluno asc;

SELECT cod_aluno ,Trunc(nascimento) AS NASCIMENTO, NOME
FROM taluno
WHERE Trunc(nascimento) = '29/08/2002'
ORDER BY cod_aluno asc;

SELECT ESTADO,Avg(POPULACAO) AS POPULACAO_TOTAL FROM SENSO
WHERE ANO ='2014'
GROUP BY ESTADO
ORDER BY 2 DESC;
