

UPDATE TALUNO SET
ESTADO = 'AC',
SALARIO = 250
WHERE COD_ALUNO = 1;

UPDATE TALUNO SET
ESTADO ='SP',
SALARIO = 460
WHERE COD_ALUNO =4;

SELECT * FROM TALUNO
WHERE ESTADO= 'PE'
AND SALARIO <=2000
ORDER BY cod_aluno  ASC ;


INSERT INTO taluno (cod_aluno, nome, cidade)
VALUES (seq_aluno.nextval, 'VALDO', 'DOIS IRMAOS');

INSERT INTO taluno (cod_aluno, nome, cidade)
VALUES (seq_aluno.nextval, 'EWERTON', 'DOIS IRMAOS');
INSERT INTO taluno (cod_aluno, nome, cidade)
VALUES (seq_aluno.nextval, 'VINICIUS', 'DOIS IRMAOS');


UPDATE taluno SET

ESTADO ='SP',
SALARIO = 900,
NOME ='PEDRO'
WHERE COD_ALUNO = 25;

SELECT ESTADO, SALARIO, NOME FROM TALUNO
ORDER BY ESTADO, SALARIO DESC;

-- criei um campo nascimento e usando o tipo DATE e por DEFAULT SYSDATE  -3000  PEGANDO TODOS OS
-- ALUNOS DESSA TABELA TALUNO E FAZENDO DECRESCER 3000 DIAS PARTINDO DA DATA ATUAL---
ALTER TABLE TALUNO ADD NASCIMENTO DATE DEFAULT SYSDATE ;
   ---
   ---- AQUI CONSEGUI SUBTRAIR
   UPDATE TALUNO SET
NASCIMENTO = SYSDATE;
WHERE COD_ALUNO=15;


UPDATE TALUNO SET
NASCIMENTO='10/08/2000'
WHERE COD_ALUNO=2;

UPDATE TALUNO SET NASCIMENTO = '10/08/2000' WHERE COD_ALUNO = 2;


                    SELECT * FROM TALUNO
                    WHERE COD_ALUNO= 2;