
        SELECT NOME, ESTADO,
         Decode(ESTADO, 'RS', 'GAUCHO',
                        'AC', 'ACREANO',
                        'SP', 'PAULISTA',
                        'PE', 'PERNAMBUCANO',
                              'OUTROS') AS APELIDO
                              FROM TALUNO;


  SELECT COD_ALUNO, NOME, CIDADE,
  Decode ( CIDADE, 'RECIFE','RECIFENCE' ,
                    'OLINDA', 'PRATICA ARRASTÃO',
                    'OUTROS') AS APELIDO
                    FROM TALUNO
                    ORDER BY COD_ALUNO;



      SELECT  * FROM TALUNO
      WHERE COD_ALUNO =16;

      UPDATE TALUNO SET
      CIDADE = 'OLINDA'
      WHERE COD_ALUNO = 16;

      UPDATE TALUNO SET
      CIDADE = NULL
      WHERE COD_ALUNO = 16;


                --- PRODUTO CARTESIANO --> ERRADO
      SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
      FROM TALUNO, TCONTRATO
      ORDER BY COD_ALUNO;

      ----
      SELECT * FROM TCONTRATO;



      -- CORRETO
           SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
            FROM TALUNO, TCONTRATO
            WHERE TALUNO.COD_ALUNO = TCONTRATO.COD_ALUNO
            ORDER BY COD_ALUNO;


            UPDATE TALUNO SET
            NOME = 'MAURICIO'
            WHERE COD_ALUNO=5;


            ----- ERRADO - COLUNA AMBIGUA
            SELECT COD_ALUNO,TALUNO.NOME, TCONTRATO.TOTAL
            FROM TALUNO, TCONTRATO
            WHERE TALUNO.COD_ALUNO = TCONTRATO.COD_ALUNO;

            ---- CORRETO, QUANDO UMA COLUNA EXISTE COM MESMO nome em mais de uma tabela,
            --- colocar prefixo na coluna
            ------------------------------------------------

     --- UNIÃO DA TABELA DE ALUNO COM CONTRATO


     SELECT ALU.COD_ALUNO,ALU.NOME ||' '||ALU.SOBRENOME AS ALUNO,
     CON.COD_CONTRATO,CON.DATA, CON.TOTAL

     FROM  TALUNO ALU, TCONTRATO CON

     WHERE CON.COD_ALUNO = ALU.COD_ALUNO  --- CRITERIO DE UNIÃO ---

     AND Upper(ALU.NOME) LIKE '%' --- FILTRO---

     ORDER BY ALU.NOME; ---ORDERNAR POR NOME--

-------------------------------------------------------------------------------

SELECT * FROM TALUNO
SELECT * FROM TCONTRATO
SELECT * FROM TITEM
SELECT * FROM TCURSO

SELECT ALU.COD_ALUNO, ALU.NOME AS ALUNO,
CON.COD_CONTRATO, CON.DATA, CON.TOTAL,
ITE.COD_CURSO, CUR.NOME AS CURSO,
ITE.VALOR

FROM TALUNO ALU, TCONTRATO CON,
 TITEM ITE, TCURSO CUR

 WHERE  ALU.COD_ALUNO = CON.COD_ALUNO(+) -- CRITERIO UNIAO
 AND CON.COD_CONTRATO = ITE.COD_CONTRATO(+)
 AND ITE.COD_CURSO = CUR.COD_CURSO(+)

 ORDER BY CON.TOTAL DESC;

