CREATE TABLE  TALUNO
(
  COD_ALUNO INTEGER NOT NULL,
  NOME VARCHAR2(30),
  CIDADE VARCHAR2(30),
  CEP VARCHAR2(20),
  PRIMARY KEY(COD_ALUNO)

);
       SELECT * FROM TALUNO
       ORDER BY COD_ALUNO;

       SELECT * FROM TALUNO
       WHERE CIDADE='JABOATAO';


    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (1,'FELIPE','RECIFE','5920670');


    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (2,'LUCAS','RECIFE','8755555');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (3,'MANOEL','RECIFE','5945670');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (4,'CINTIA','RECIFE','7854525');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (5,'ELIAS','JABOATAO','4564688');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (6,'RODRIGO','CAMARAGIBE','56464844');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (7,'FERNANDA','RECIFE','654645123');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (8,'WILLIAMS','JABOATAO','456456113');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (9,'ANA','RECIFE','5920670');


    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (10,'NIVIA','RECIFE','46515131');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (11,'RICARDO','CAMARAGIBE','5484561');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (12,'TIAGO','RECIFE','84151561');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (13,'LIZANDRA','RECIFE','46546848');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (14,'CARLOS','RECIFE','5920670');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (15,'LILIAN','JABOATAO','45648941');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (16,'KAROL','CAMARAGIBE','51551321');

    INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
    VALUES (17,'MARCIA','RECIFE','21684865');