

---- capitulo 10 ----

  TALUNO
  -- COD_ALUNO - PK   -- CHAVE PRIMARIA  --> PRIMARY KEY


  TCONTRATO
  -- COD_CONTRATO - PK   -- CHAVE PRIMARIA  --> PRIMARY KEY
  -- COD_ALUNO - FK -> CHAVE PRIMARIA QUE VEM DE OUTRA TABELA

  SELECT * FROM USER_CONSTRAINTS;

  SELECT * FROM ALL_CONSTRAINTS;



  -----------------------------------------
            DROP TABLE TCIDADE;

            CREATE TABLE TCIDADE (

            COD_CIDADE INTEGER NOT NULL,
            NOME VARCHAR2 (40),
            CONSTRAINT PK_CIDADE PRIMARY KEY (COD_CIDADE)
            );

  CREATE TABLE TBAIRRO (
  COD_CIDADE INTEGER NOT NULL,
  COD_BAIRRO INTEGER NOT NULL,
  NOME  VARCHAR2(20),
  CONSTRAINTS PK_BAIRRO PRIMARY KEY (COD_CIDADE, COD_BAIRRO)
  );


  SELECT * FROM TCIDADE;


  SELECT * FROM TBAIRRO;

