

---- capitulo 10 ----

  TALUNO
  -- COD_ALUNO - PK   -- CHAVE PRIMARIA  --> PRIMARY KEY


  TCONTRATO
  -- COD_CONTRATO - PK   -- CHAVE PRIMARIA  --> PRIMARY KEY
  -- COD_ALUNO - FK -> CHAVE PRIMARIA QUE VEM DE OUTRA TABELA

  SELECT * FROM USER_CONSTRAINTS;

  SELECT * FROM ALL_CONSTRAINTS;



  -----------------------------------------
            DROP TABLE TCIDADE;

            CREATE TABLE TCIDADE (

            COD_CIDADE INTEGER NOT NULL,
            NOME VARCHAR2 (40),
            CONSTRAINT PK_CIDADE PRIMARY KEY (COD_CIDADE)
            );

  CREATE TABLE TBAIRRO (
  COD_CIDADE INTEGER NOT NULL,
  COD_BAIRRO INTEGER NOT NULL,
  NOME  VARCHAR2(20),
  CONSTRAINTS PK_BAIRRO PRIMARY KEY (COD_CIDADE, COD_BAIRRO)
  );

  ---- add chave estrangeira
  ALTER TABLE TBAIRRO ADD CONSTRAINT FK_COD_CIDADE
  FOREIGN KEY (COD_CIDADE)
  REFERENCES TCIDADE(COD_CIDADE);


  SELECT * FROM TCIDADE;
  ROLLBACK;

  SELECT * FROM TBAIRRO;

  CREATE TABLE TRUA(
  COD_RUA INTEGER NOT NULL,
  COD_CIDADE INTEGER ,
  COD_BAIRRO INTEGER ,
  NOME VARCHAR2(40),
  CONSTRAINT PK_RUA PRIMARY KEY(COD_RUA)
  );

  ALTER TABLE TRUA ADD CONSTRAINT FK_CIDADEBAIRRO
  FOREIGN KEY (COD_CIDADE,COD_BAIRRO)
  REFERENCES TBAIRRO(COD_CIDADE, COD_BAIRRO);

  -- DROP TABLE TPESSOA ( FORNEC OU CLIENTE)


  CREATE TABLE TPESSOA (
  COD_PESSOA      INTEGER        NOT NULL,
  TIPO            VARCHAR2(1)    NOT NULL,
  NOME            VARCHAR2(30)   NOT NULL,
  PESSOA          VARCHAR2(1)    NOT NULL,
  COD_RUA         INTEGER        NOT NULL,
  CPF             VARCHAR2(15) ,
  CONSTRAINT PK_PESSOA PRIMARY KEY (COD_PESSOA)
  );


  ---- UNIQUE KEY ---
  -- PARA QUE SEJA APAENA CPF UNICOS E NÃO EXISTE DUPLICADOS----
  ALTER TABLE  TPESSOA ADD CONSTRAINT UK_CPF UNIQUE(CPF);
