-- CAPITULO 20

CREATE OR REPLACE PROCEDURE CONSULTA_ALUNO
(PCOD_ALUNO       IN TALUNO.COD_ALUNO%TYPE,
  PNOME           OUT TALUNO.NOME%TYPE,
  PNASCIMENTO     OUT TALUNO.NASCIMENTO%TYPE,
  PCIDADE         OUT TALUNO.CIDADE%TYPE)

  IS
  BEGIN
    SELECT NOME,NASCIMENTO, CIDADE
    INTO PNOME,PNASCIMENTO,PCIDADE
    FROM TALUNO
    WHERE COD_ALUNO = PCOD_ALUNO;
  END CONSULTA_ALUNO;


  SELECT CONSULTA_ALUNO FROM TALUNO

CREATE  OR REPLACE PROCEDURE  ATUALIZA_PREÇO_CURSO
IS
BEGIN
