

--- capitulo 11
CREATE  OR REPLACE VIEW VW_ALUNO
AS
  SELECT COD_ALUNO AS CODIGO, SALARIO,
          NOME AS ALUNO, CIDADE
  FROM TALUNO
  WHERE ESTADO='PE';

  SELECT * FROM VW_ALUNO
  ORDER BY ALUNO;